--Run with user SBREXT

GRANT DELETE, INSERT, SELECT, UPDATE ON SBREXT.CUSTOM_DOWNLOAD_TYPES TO DER_USER;

GRANT DELETE, INSERT, SELECT, UPDATE ON SBREXT.CDE_EXCEL_GENERATOR_VIEW TO CDECURATE;

GRANT DELETE, INSERT, SELECT, UPDATE ON SBREXT.CDE_EXCEL_GENERATOR_VIEW TO DER_USER;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SBREXT.CDE_EXCEL_GENERATOR_VIEW TO SBR WITH GRANT OPTION;

GRANT DELETE, INSERT, SELECT, UPDATE ON SBREXT.DEC_EXCEL_GENERATOR_VIEW TO CDECURATE;

GRANT DELETE, INSERT, SELECT, UPDATE ON SBREXT.DEC_EXCEL_GENERATOR_VIEW TO DER_USER;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SBREXT.DEC_EXCEL_GENERATOR_VIEW TO SBR WITH GRANT OPTION;

GRANT DELETE, INSERT, SELECT, UPDATE ON SBREXT.VD_EXCEL_GENERATOR_VIEW TO CDECURATE;

GRANT DELETE, INSERT, SELECT, UPDATE ON SBREXT.VD_EXCEL_GENERATOR_VIEW TO DER_USER;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SBREXT.VD_EXCEL_GENERATOR_VIEW TO SBR WITH GRANT OPTION;

  GRANT DELETE ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT INSERT ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT SELECT ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT UPDATE ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT REFERENCES ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT ON COMMIT REFRESH ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT QUERY REWRITE ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT DEBUG ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT FLASHBACK ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT MERGE VIEW ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT DELETE ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT INSERT ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT SELECT ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT UPDATE ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT REFERENCES ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT ON COMMIT REFRESH ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT QUERY REWRITE ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT DEBUG ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT FLASHBACK ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT MERGE VIEW ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT DELETE ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "DER_USER";
 
  GRANT INSERT ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "DER_USER";
 
  GRANT SELECT ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "DER_USER";
 
  GRANT UPDATE ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "DER_USER";
 
  GRANT MERGE VIEW ON "SBREXT"."DE_EXCEL_GENERATOR_VIEW" TO "DER_USER";

  GRANT DELETE ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT INSERT ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT SELECT ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT UPDATE ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT REFERENCES ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT ON COMMIT REFRESH ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT QUERY REWRITE ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT DEBUG ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT FLASHBACK ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT MERGE VIEW ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "CDEBROWSER";
 
  GRANT DELETE ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT INSERT ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT SELECT ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT UPDATE ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT REFERENCES ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT ON COMMIT REFRESH ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT QUERY REWRITE ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT DEBUG ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT FLASHBACK ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT MERGE VIEW ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "SBR" WITH GRANT OPTION;
 
  GRANT DELETE ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "DER_USER";
 
  GRANT INSERT ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "DER_USER";
 
  GRANT SELECT ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "DER_USER";
 
  GRANT UPDATE ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "DER_USER";
 
  GRANT MERGE VIEW ON "SBREXT"."DE_XML_GENERATOR_VIEW" TO "DER_USER";

  GRANT EXECUTE, DEBUG ON SBREXT.CDEBROWSER_VD_T TO CDEBROWSER;
 
GRANT EXECUTE, DEBUG ON SBREXT.CDEBROWSER_VD_T TO DER_USER;
 
GRANT EXECUTE, DEBUG ON  sbrext.valid_value_list_t TO CDEBROWSER;
 
GRANT EXECUTE, DEBUG ON  sbrext.valid_value_list_t TO DER_USER;
 
GRANT EXECUTE, DEBUG ON  sbrext.valid_value_t TO CDEBROWSER;
 
GRANT EXECUTE, DEBUG ON  sbrext.valid_value_t TO DER_USER;
