-- run this as SBREXT user
/*
 * Fix related to issue https://gforge.nci.nih.gov/tracker/index.php?func=detail&aid=30681.
 */
CREATE OR REPLACE PACKAGE DEC_ACTIONS AS  -- spec
PROCEDURE SET_DEC(
P_UA_NAME          IN VARCHAR2
,P_RETURN_CODE        OUT    VARCHAR2
,P_ACTION                   IN     VARCHAR2
,P_DEC_DEC_IDSEQ         IN OUT VARCHAR2
,P_DEC_PREFERRED_NAME     IN OUT VARCHAR2
,P_DEC_CONTE_IDSEQ         IN OUT VARCHAR2
,P_DEC_VERSION             IN OUT NUMBER
,P_DEC_PREFERRED_DEFINITION IN OUT VARCHAR2
,P_DEC_CD_IDSEQ             IN OUT VARCHAR2
,P_DEC_ASL_NAME             IN OUT VARCHAR2
,P_DEC_LATEST_VERSION_IND   IN OUT VARCHAR2
,P_DEC_LONG_NAME         IN OUT VARCHAR2
,P_DEC_OC_IDSEQ             IN OUT VARCHAR2
,P_DEC_PROP_IDSEQ           IN OUT VARCHAR2
,P_DEC_PROPERTY_QUALIFIER IN OUT VARCHAR2
,P_DEC_OBJ_CLASS_QUALIFIER IN OUT VARCHAR2
,P_DEC_BEGIN_DATE         IN OUT VARCHAR2
,P_DEC_END_DATE             IN OUT VARCHAR2
,P_DEC_CHANGE_NOTE         IN OUT VARCHAR2
,P_DEC_CREATED_BY         OUT    VARCHAR2
,P_DEC_DATE_CREATED         OUT    VARCHAR2
,P_DEC_MODIFIED_BY         OUT    VARCHAR2
,P_DEC_DATE_MODIFIED     OUT    VARCHAR2
,P_DEC_DELETED_IND         OUT    VARCHAR2
,P_DEC_ORIGIN               IN     VARCHAR2 DEFAULT NULL	-- 15-Jul-2003, W. Ver Hoef
,P_DEC_CDR_NAME               IN     VARCHAR2  --GF30681
);
 END DEC_ACTIONS;
/

  GRANT EXECUTE ON "SBREXT"."DEC_ACTIONS" TO PUBLIC;
/ 
  GRANT EXECUTE ON "SBREXT"."DEC_ACTIONS" TO "CDEBROWSER";
/ 
  GRANT DEBUG ON "SBREXT"."DEC_ACTIONS" TO "CDEBROWSER";
/ 
  GRANT EXECUTE ON "SBREXT"."DEC_ACTIONS" TO "DATA_LOADER";
/
  GRANT DEBUG ON "SBREXT"."DEC_ACTIONS" TO "DATA_LOADER";
/ 
  GRANT EXECUTE ON "SBREXT"."DEC_ACTIONS" TO "SBR" WITH GRANT OPTION;
/ 
  GRANT DEBUG ON "SBREXT"."DEC_ACTIONS" TO "SBR" WITH GRANT OPTION;
/ 
  GRANT EXECUTE ON "SBREXT"."DEC_ACTIONS" TO "APPLICATION_USER";
/ 
  GRANT DEBUG ON "SBREXT"."DEC_ACTIONS" TO "APPLICATION_USER";
/ 
  GRANT EXECUTE ON "SBREXT"."DEC_ACTIONS" TO "DER_USER";
/
