--------------------------------------------------------
--  File created - Thursday-April-04-2013   
--------------------------------------------------------
--------------------------------------------------------
--  Ref Constraints for Table AC_ATT_CSCSI_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."AC_ATT_CSCSI_EXT" ADD CONSTRAINT "AAI_AAL_FK" FOREIGN KEY ("ATL_NAME")
	  REFERENCES "SBREXT"."AC_ATT_TYPES_LOV_EXT" ("ATL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."AC_ATT_CSCSI_EXT" ADD CONSTRAINT "AAI_CS_CSI_FK" FOREIGN KEY ("CS_CSI_IDSEQ")
	  REFERENCES "SBR"."CS_CSI" ("CS_CSI_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AC_SOURCES_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."AC_SOURCES_EXT" ADD CONSTRAINT "AST_ACT_FK" FOREIGN KEY ("AC_IDSEQ")
	  REFERENCES "SBR"."ADMINISTERED_COMPONENTS" ("AC_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASL_ACTL_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."ASL_ACTL_EXT" ADD CONSTRAINT "AAT_ASL_FK" FOREIGN KEY ("ASL_NAME")
	  REFERENCES "SBR"."AC_STATUS_LOV" ("ASL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."ASL_ACTL_EXT" ADD CONSTRAINT "AAT_ATL_FK" FOREIGN KEY ("ACTL_NAME")
	  REFERENCES "SBR"."AC_TYPES_LOV" ("ACTL_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CDE_CART_ITEMS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CDE_CART_ITEMS" ADD CONSTRAINT "CCM_ACTL_FK" FOREIGN KEY ("ACTL_NAME")
	  REFERENCES "SBR"."AC_TYPES_LOV" ("ACTL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."CDE_CART_ITEMS" ADD CONSTRAINT "CCM_AC_FK" FOREIGN KEY ("AC_IDSEQ")
	  REFERENCES "SBR"."ADMINISTERED_COMPONENTS" ("AC_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."CDE_CART_ITEMS" ADD CONSTRAINT "CCM_UA_FK" FOREIGN KEY ("UA_NAME")
	  REFERENCES "SBR"."USER_ACCOUNTS" ("UA_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLASS_SCHEMES_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CLASS_SCHEMES_STAGING" ADD CONSTRAINT "CSC_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPONENT_CONCEPTS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."COMPONENT_CONCEPTS_EXT" ADD CONSTRAINT "CCT_CET_FK" FOREIGN KEY ("CON_IDSEQ")
	  REFERENCES "SBREXT"."CONCEPTS_EXT" ("CON_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."COMPONENT_CONCEPTS_EXT" ADD CONSTRAINT "CCT_CLT_FK" FOREIGN KEY ("CL_IDSEQ")
	  REFERENCES "SBREXT"."COMPONENT_LEVELS_EXT" ("CL_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."COMPONENT_CONCEPTS_EXT" ADD CONSTRAINT "CCT_CONDR_FK" FOREIGN KEY ("CONDR_IDSEQ")
	  REFERENCES "SBREXT"."CON_DERIVATION_RULES_EXT" ("CONDR_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONCEPTS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CONCEPTS_EXT" ADD CONSTRAINT "CON_ASV_FK" FOREIGN KEY ("ASL_NAME")
	  REFERENCES "SBR"."AC_STATUS_LOV" ("ASL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."CONCEPTS_EXT" ADD CONSTRAINT "CON_COT_FK" FOREIGN KEY ("CONTE_IDSEQ")
	  REFERENCES "SBR"."CONTEXTS" ("CONTE_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONCEPTUAL_DOMAINS_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CONCEPTUAL_DOMAINS_STAGING" ADD CONSTRAINT "CD_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONDITION_COMPONENTS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CONDITION_COMPONENTS_EXT" ADD CONSTRAINT "QCT_QCON_FK" FOREIGN KEY ("P_QCON_IDSEQ")
	  REFERENCES "SBREXT"."QUESTION_CONDITIONS_EXT" ("QCON_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."CONDITION_COMPONENTS_EXT" ADD CONSTRAINT "QCT_QCON_FK2" FOREIGN KEY ("C_QCON_IDSEQ")
	  REFERENCES "SBREXT"."QUESTION_CONDITIONS_EXT" ("QCON_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."CONDITION_COMPONENTS_EXT" ADD CONSTRAINT "QCT_RFT_FK" FOREIGN KEY ("RF_IDSEQ")
	  REFERENCES "SBREXT"."RULE_FUNCTIONS_EXT" ("RF_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."CONDITION_COMPONENTS_EXT" ADD CONSTRAINT "QCT_VVT_FK" FOREIGN KEY ("VV_IDSEQ")
	  REFERENCES "SBREXT"."VALID_VALUES_ATT_EXT" ("QC_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONDITION_MESSAGE_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CONDITION_MESSAGE_EXT" ADD CONSTRAINT "CMT_MTT_FK" FOREIGN KEY ("MT_NAME")
	  REFERENCES "SBREXT"."MESSAGE_TYPES_EXT" ("MT_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."CONDITION_MESSAGE_EXT" ADD CONSTRAINT "CMT_QCON_FK" FOREIGN KEY ("QCON_IDSEQ")
	  REFERENCES "SBREXT"."QUESTION_CONDITIONS_EXT" ("QCON_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CON_DERIVATION_RULES_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CON_DERIVATION_RULES_EXT" ADD CONSTRAINT "CONDR_CRV_FK" FOREIGN KEY ("CRTL_NAME")
	  REFERENCES "SBR"."COMPLEX_REP_TYPE_LOV" ("CRTL_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CRF_TOOL_PARAMETER_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CRF_TOOL_PARAMETER_EXT" ADD CONSTRAINT "CTP_UAT_FK" FOREIGN KEY ("UA_NAME")
	  REFERENCES "SBR"."USER_ACCOUNTS" ("UA_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CSIR_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CSIR_STAGING" ADD CONSTRAINT "CSR_CSC_FK" FOREIGN KEY ("CST_ID")
	  REFERENCES "SBREXT"."CSI_STAGING" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CSI_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."CSI_STAGING" ADD CONSTRAINT "CST_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DATA_ELEMENTS_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."DATA_ELEMENTS_STAGING" ADD CONSTRAINT "DE_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DATA_ELEMENT_CONCEPTS_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."DATA_ELEMENT_CONCEPTS_STAGING" ADD CONSTRAINT "DEC_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DECR_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."DECR_STAGING" ADD CONSTRAINT "DCR_DCS_FK" FOREIGN KEY ("DCS_ID")
	  REFERENCES "SBREXT"."DEC_STAGING" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEC_RELATIONSHIPS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."DEC_RELATIONSHIPS" ADD CONSTRAINT "DER_DEC_FK" FOREIGN KEY ("DEC_ID")
	  REFERENCES "SBREXT"."DATA_ELEMENT_CONCEPTS_STAGING" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEC_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."DEC_STAGING" ADD CONSTRAINT "DCS_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EATTRIBUTES_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EATTRIBUTES_STAGING" ADD CONSTRAINT "EAT_ECL_FK" FOREIGN KEY ("ECL_ID")
	  REFERENCES "SBREXT"."ECLASSES_STAGING" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ECLASSES_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."ECLASSES_STAGING" ADD CONSTRAINT "ECL_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EREFERENCES_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EREFERENCES_STAGING" ADD CONSTRAINT "ERE_ECL_FK" FOREIGN KEY ("ECL_ID")
	  REFERENCES "SBREXT"."ECLASSES_STAGING" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESUPERTYPES_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."ESUPERTYPES_STAGING" ADD CONSTRAINT "ESU_ECL_FK" FOREIGN KEY ("ECL_ID")
	  REFERENCES "SBREXT"."ECLASSES_STAGING" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_ACCESS_PRIVS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_AP_EU_FK" FOREIGN KEY ("AP_EU_ID")
	  REFERENCES "SBREXT"."EUL4_EUL_USERS" ("EU_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_GBA_BA_FK" FOREIGN KEY ("GBA_BA_ID")
	  REFERENCES "SBREXT"."EUL4_BAS" ("BA_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_GD_DOC_FK" FOREIGN KEY ("GD_DOC_ID")
	  REFERENCES "SBREXT"."EUL4_DOCUMENTS" ("DOC_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_GP_PRI_FK" FOREIGN KEY ("GP_APP_ID")
	  REFERENCES "SBREXT"."EUL4_APP_PARAMS" ("APP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_ASMP_CONS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_AOC_OBJ_FK" FOREIGN KEY ("AOC_OBJ_ID")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_APC_ASMP_FK" FOREIGN KEY ("APC_ASMP_ID")
	  REFERENCES "SBREXT"."EUL4_ASM_POLICIES" ("ASMP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_ASOC_SUMO_FK" FOREIGN KEY ("ASOC_SUMO_ID")
	  REFERENCES "SBREXT"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_AUC_EU_FK" FOREIGN KEY ("AUC_EU_ID")
	  REFERENCES "SBREXT"."EUL4_EUL_USERS" ("EU_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_ASMP_LOGS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_ASMP_LOGS" ADD CONSTRAINT "EUL4_APL_ASMP_FK" FOREIGN KEY ("APL_ASMP_ID")
	  REFERENCES "SBREXT"."EUL4_ASM_POLICIES" ("ASMP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_ASMP_LOGS" ADD CONSTRAINT "EUL4_APL_SUMO_FK" FOREIGN KEY ("APL_SUMO_ID")
	  REFERENCES "SBREXT"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_BATCH_PARAMS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_BATCH_PARAMS" ADD CONSTRAINT "EUL4_BP_BS_FK" FOREIGN KEY ("BP_BS_ID")
	  REFERENCES "SBREXT"."EUL4_BATCH_SHEETS" ("BS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_BATCH_QUERIES
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_BATCH_QUERIES" ADD CONSTRAINT "EUL4_BQ_BS_FK" FOREIGN KEY ("BQ_BS_ID")
	  REFERENCES "SBREXT"."EUL4_BATCH_SHEETS" ("BS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_BATCH_REPORTS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_BATCH_REPORTS" ADD CONSTRAINT "EUL4_BR_EU_FK" FOREIGN KEY ("BR_EU_ID")
	  REFERENCES "SBREXT"."EUL4_EUL_USERS" ("EU_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_BATCH_REPORTS" ADD CONSTRAINT "EUL4_BR_RFU_FK" FOREIGN KEY ("BR_RFU_ID")
	  REFERENCES "SBREXT"."EUL4_FREQ_UNITS" ("RFU_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_BATCH_SHEETS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_BATCH_SHEETS" ADD CONSTRAINT "EUL4_BS_BR_FK" FOREIGN KEY ("BS_BR_ID")
	  REFERENCES "SBREXT"."EUL4_BATCH_REPORTS" ("BR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_BA_OBJ_LINKS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_BA_OBJ_LINKS" ADD CONSTRAINT "EUL4_BOL_BA_FK" FOREIGN KEY ("BOL_BA_ID")
	  REFERENCES "SBREXT"."EUL4_BAS" ("BA_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_BA_OBJ_LINKS" ADD CONSTRAINT "EUL4_BOL_OBJ_FK" FOREIGN KEY ("BOL_OBJ_ID")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_BQ_DEPS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BFILD_FIL_FK" FOREIGN KEY ("BFILD_FIL_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BFUND_FUN_FK" FOREIGN KEY ("BFUND_FUN_ID")
	  REFERENCES "SBREXT"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BID_IT_FK" FOREIGN KEY ("BID_IT_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BQD_BQ_FK" FOREIGN KEY ("BQD_BQ_ID")
	  REFERENCES "SBREXT"."EUL4_BATCH_QUERIES" ("BQ_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_BQ_TABLES
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_BQ_TABLES" ADD CONSTRAINT "EUL4_BQT_BQ_FK" FOREIGN KEY ("BQT_BQ_ID")
	  REFERENCES "SBREXT"."EUL4_BATCH_QUERIES" ("BQ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_BQ_TABLES" ADD CONSTRAINT "EUL4_BQT_BRR_FK" FOREIGN KEY ("BQT_BRR_ID")
	  REFERENCES "SBREXT"."EUL4_BR_RUNS" ("BRR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_BR_RUNS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_BR_RUNS" ADD CONSTRAINT "EUL4_BRR_BR_FK" FOREIGN KEY ("BRR_BR_ID")
	  REFERENCES "SBREXT"."EUL4_BATCH_REPORTS" ("BR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_DBH_NODES
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_DBH_NODES" ADD CONSTRAINT "EUL4_DHN_DBH_FK" FOREIGN KEY ("DHN_HI_ID")
	  REFERENCES "SBREXT"."EUL4_HIERARCHIES" ("HI_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_DOCUMENTS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_DOCUMENTS" ADD CONSTRAINT "EUL4_DOC_EU_FK" FOREIGN KEY ("DOC_EU_ID")
	  REFERENCES "SBREXT"."EUL4_EUL_USERS" ("EU_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_DOMAINS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_IT_L_FK" FOREIGN KEY ("DOM_IT_ID_LOV")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_IT_R_FK" FOREIGN KEY ("DOM_IT_ID_RANK")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_EXPRESSIONS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_CI_IT_FK" FOREIGN KEY ("CI_IT_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_FIL_DOC_FK" FOREIGN KEY ("FIL_DOC_ID")
	  REFERENCES "SBREXT"."EUL4_DOCUMENTS" ("DOC_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_FIL_OBJ_FK" FOREIGN KEY ("FIL_OBJ_ID")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_IT_DOC_FK" FOREIGN KEY ("IT_DOC_ID")
	  REFERENCES "SBREXT"."EUL4_DOCUMENTS" ("DOC_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_IT_DOM_FK" FOREIGN KEY ("IT_DOM_ID")
	  REFERENCES "SBREXT"."EUL4_DOMAINS" ("DOM_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_IT_FUN_FK" FOREIGN KEY ("IT_FUN_ID")
	  REFERENCES "SBREXT"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_IT_OBJ_FK" FOREIGN KEY ("IT_OBJ_ID")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_JP_FK_FK" FOREIGN KEY ("JP_KEY_ID")
	  REFERENCES "SBREXT"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_EXP_DEPS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_CD_CI_FK" FOREIGN KEY ("CD_EXP_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_CFD_FUN_FK" FOREIGN KEY ("CFD_FUN_ID")
	  REFERENCES "SBREXT"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_CID_IT_FK" FOREIGN KEY ("CID_EXP_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_PD_P_FK" FOREIGN KEY ("PD_P_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_PED_EXP_FK" FOREIGN KEY ("PED_EXP_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_PFD_FUN_FK" FOREIGN KEY ("PFD_FUN_ID")
	  REFERENCES "SBREXT"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_PSD_SQ_FK" FOREIGN KEY ("PSD_SQ_ID")
	  REFERENCES "SBREXT"."EUL4_SUB_QUERIES" ("SQ_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_FUN_ARGUMENTS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_FUN_ARGUMENTS" ADD CONSTRAINT "EUL4_FA_FUN_FK" FOREIGN KEY ("FA_FUN_ID")
	  REFERENCES "SBREXT"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_FUN_FC_LINKS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_FUN_FC_LINKS" ADD CONSTRAINT "EUL4_FFL_FC_FK" FOREIGN KEY ("FFL_FC_ID")
	  REFERENCES "SBREXT"."EUL4_FUN_CTGS" ("FC_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_FUN_FC_LINKS" ADD CONSTRAINT "EUL4_FFL_FUN_FK" FOREIGN KEY ("FFL_FUN_ID")
	  REFERENCES "SBREXT"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_HIERARCHIES
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_HIERARCHIES" ADD CONSTRAINT "EUL4_IBH_DBH_FK" FOREIGN KEY ("IBH_DBH_ID")
	  REFERENCES "SBREXT"."EUL4_HIERARCHIES" ("HI_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_HI_NODES
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_HI_NODES" ADD CONSTRAINT "EUL4_HN_IBH_FK" FOREIGN KEY ("HN_HI_ID")
	  REFERENCES "SBREXT"."EUL4_HIERARCHIES" ("HI_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_HI_SEGMENTS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_DHS_DBH_FK" FOREIGN KEY ("DHS_HI_ID")
	  REFERENCES "SBREXT"."EUL4_HIERARCHIES" ("HI_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_DHS_DHN_C_FK" FOREIGN KEY ("DHS_DHN_ID_PARENT")
	  REFERENCES "SBREXT"."EUL4_DBH_NODES" ("DHN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_DHS_DHN_P_FK" FOREIGN KEY ("DHS_DHN_ID_CHILD")
	  REFERENCES "SBREXT"."EUL4_DBH_NODES" ("DHN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_IHS_HN_C_FK" FOREIGN KEY ("IHS_HN_ID_PARENT")
	  REFERENCES "SBREXT"."EUL4_HI_NODES" ("HN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_IHS_HN_P_FK" FOREIGN KEY ("IHS_HN_ID_CHILD")
	  REFERENCES "SBREXT"."EUL4_HI_NODES" ("HN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_IHS_IBH_FK" FOREIGN KEY ("IHS_HI_ID")
	  REFERENCES "SBREXT"."EUL4_HIERARCHIES" ("HI_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_IG_EXP_LINKS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_HIL_HN_FK" FOREIGN KEY ("HIL_HN_ID")
	  REFERENCES "SBREXT"."EUL4_HI_NODES" ("HN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_HIL_IT_FK" FOREIGN KEY ("HIL_EXP_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_KIL_IT_FK" FOREIGN KEY ("KIL_EXP_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_KIL_KEY_FK" FOREIGN KEY ("KIL_KEY_ID")
	  REFERENCES "SBREXT"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_IHS_FK_LINKS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_IHS_FK_LINKS" ADD CONSTRAINT "EUL4_IFL_FK_FK" FOREIGN KEY ("IFL_KEY_ID")
	  REFERENCES "SBREXT"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_IHS_FK_LINKS" ADD CONSTRAINT "EUL4_IFL_IHS_FK" FOREIGN KEY ("IFL_IHS_ID")
	  REFERENCES "SBREXT"."EUL4_HI_SEGMENTS" ("HS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_KEY_CONS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_KEY_CONS" ADD CONSTRAINT "EUL4_FK_OBJ_FK" FOREIGN KEY ("FK_OBJ_ID_REMOTE")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_KEY_CONS" ADD CONSTRAINT "EUL4_FK_UK_FK" FOREIGN KEY ("FK_KEY_ID_REMOTE")
	  REFERENCES "SBREXT"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_KEY_CONS" ADD CONSTRAINT "EUL4_KEY_OBJ_FK" FOREIGN KEY ("KEY_OBJ_ID")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_OBJS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_OBJS" ADD CONSTRAINT "EUL4_OBJ_BA_FK" FOREIGN KEY ("OBJ_BA_ID")
	  REFERENCES "SBREXT"."EUL4_BAS" ("BA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_OBJ_DEPS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_OBJ_DEPS" ADD CONSTRAINT "EUL4_OD_COBJ_FK" FOREIGN KEY ("OD_OBJ_ID_FROM")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_OBJ_DEPS" ADD CONSTRAINT "EUL4_OD_OBJ_FK" FOREIGN KEY ("OD_OBJ_ID_TO")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_OBJ_JOIN_USGS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_COBJ_FK" FOREIGN KEY ("OJU_OBJ_ID")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_FK_FK" FOREIGN KEY ("OJU_KEY_ID")
	  REFERENCES "SBREXT"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_SUMO_FK" FOREIGN KEY ("OJU_SUMO_ID")
	  REFERENCES "SBREXT"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_SEGMENTS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_SEGMENTS" ADD CONSTRAINT "EUL4_SEG_BQ_FK" FOREIGN KEY ("SEG_BQ_ID")
	  REFERENCES "SBREXT"."EUL4_BATCH_QUERIES" ("BQ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SEGMENTS" ADD CONSTRAINT "EUL4_SEG_CUO_FK" FOREIGN KEY ("SEG_CUO_ID")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SEGMENTS" ADD CONSTRAINT "EUL4_SEG_EXP_FK" FOREIGN KEY ("SEG_EXP_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SEGMENTS" ADD CONSTRAINT "EUL4_SEG_OBJ_FK" FOREIGN KEY ("SEG_OBJ_ID")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SEGMENTS" ADD CONSTRAINT "EUL4_SEG_SDO_FK" FOREIGN KEY ("SEG_SUMO_ID")
	  REFERENCES "SBREXT"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SEGMENTS" ADD CONSTRAINT "EUL4_SEG_SMS_FK" FOREIGN KEY ("SEG_SMS_ID")
	  REFERENCES "SBREXT"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_SQ_CRRLTNS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_SQ_CRRLTNS" ADD CONSTRAINT "EUL4_SQC_IT_I_FK" FOREIGN KEY ("SQC_IT_INNER_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SQ_CRRLTNS" ADD CONSTRAINT "EUL4_SQC_IT_O_FK" FOREIGN KEY ("SQC_IT_OUTER_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SQ_CRRLTNS" ADD CONSTRAINT "EUL4_SQC_SQ_FK" FOREIGN KEY ("SQC_SQ_ID")
	  REFERENCES "SBREXT"."EUL4_SUB_QUERIES" ("SQ_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_SUB_QUERIES
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_SUB_QUERIES" ADD CONSTRAINT "EUL4_SQ_FIL_FK" FOREIGN KEY ("SQ_FIL_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUB_QUERIES" ADD CONSTRAINT "EUL4_SQ_IT_FK" FOREIGN KEY ("SQ_IT_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUB_QUERIES" ADD CONSTRAINT "EUL4_SQ_OBJ_FK" FOREIGN KEY ("SQ_OBJ_ID")
	  REFERENCES "SBREXT"."EUL4_OBJS" ("OBJ_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_SUMMARY_OBJS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_SUMMARY_OBJS" ADD CONSTRAINT "EUL4_SBO_SRS_FK" FOREIGN KEY ("SBO_SRS_ID")
	  REFERENCES "SBREXT"."EUL4_SUM_RFSH_SETS" ("SRS_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUMMARY_OBJS" ADD CONSTRAINT "EUL4_SDO_SBO_FK" FOREIGN KEY ("SDO_SBO_ID")
	  REFERENCES "SBREXT"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUMMARY_OBJS" ADD CONSTRAINT "EUL4_SUMO_ASMP_FK" FOREIGN KEY ("SUMO_ASMP_ID")
	  REFERENCES "SBREXT"."EUL4_ASM_POLICIES" ("ASMP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_SUMO_EXP_USGS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SEU_SUMO_FK" FOREIGN KEY ("SEU_SUMO_ID")
	  REFERENCES "SBREXT"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SFU_FUN_FK" FOREIGN KEY ("SFU_FUN_ID")
	  REFERENCES "SBREXT"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SIU_IT_FK" FOREIGN KEY ("SIU_EXP_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SMIU_FUN_FK" FOREIGN KEY ("SMIU_FUN_ID")
	  REFERENCES "SBREXT"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_SUM_BITMAPS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_SUM_BITMAPS" ADD CONSTRAINT "EUL4_SB_FK_FK" FOREIGN KEY ("SB_KEY_ID")
	  REFERENCES "SBREXT"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUM_BITMAPS" ADD CONSTRAINT "EUL4_SB_FUN_FK" FOREIGN KEY ("SB_FUN_ID")
	  REFERENCES "SBREXT"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUM_BITMAPS" ADD CONSTRAINT "EUL4_SB_IT_FK" FOREIGN KEY ("SB_EXP_ID")
	  REFERENCES "SBREXT"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EUL4_SUM_RFSH_SETS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_EU_FK" FOREIGN KEY ("SRS_EU_ID")
	  REFERENCES "SBREXT"."EUL4_EUL_USERS" ("EU_ID") ENABLE;
 
  ALTER TABLE "SBREXT"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_RFU_FK" FOREIGN KEY ("SRS_RFU_ID")
	  REFERENCES "SBREXT"."EUL4_FREQ_UNITS" ("RFU_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GS_COMPOSITE
--------------------------------------------------------

  ALTER TABLE "SBREXT"."GS_COMPOSITE" ADD CONSTRAINT "GCE_GTV_FK" FOREIGN KEY ("AC_TABLE")
	  REFERENCES "SBREXT"."GS_TABLES_LOV" ("AC_TABLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GS_TOKENS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."GS_TOKENS" ADD CONSTRAINT "GTN_GTV_FK" FOREIGN KEY ("AC_TABLE")
	  REFERENCES "SBREXT"."GS_TABLES_LOV" ("AC_TABLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOADER_DEFAULTS
--------------------------------------------------------

  ALTER TABLE "SBREXT"."LOADER_DEFAULTS" ADD CONSTRAINT "LDT_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATCH_RESULTS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."MATCH_RESULTS_EXT" ADD CONSTRAINT "MRT_ASV_FK" FOREIGN KEY ("ASL_NAME_OF_MATCH")
	  REFERENCES "SBR"."AC_STATUS_LOV" ("ASL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."MATCH_RESULTS_EXT" ADD CONSTRAINT "MRT_DET_FK" FOREIGN KEY ("DE_MATCH_IDSEQ")
	  REFERENCES "SBR"."DATA_ELEMENTS" ("DE_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."MATCH_RESULTS_EXT" ADD CONSTRAINT "MRT_RDT_FK" FOREIGN KEY ("RD_MATCH_IDSEQ")
	  REFERENCES "SBR"."REFERENCE_DOCUMENTS" ("RD_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."MATCH_RESULTS_EXT" ADD CONSTRAINT "MRT_VDN_FK" FOREIGN KEY ("VD_MATCH_IDSEQ")
	  REFERENCES "SBR"."VALUE_DOMAINS" ("VD_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBJECT_CLASSES_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."OBJECT_CLASSES_EXT" ADD CONSTRAINT "OCT_ASV_FK" FOREIGN KEY ("ASL_NAME")
	  REFERENCES "SBR"."AC_STATUS_LOV" ("ASL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."OBJECT_CLASSES_EXT" ADD CONSTRAINT "OCT_CONDR_FK" FOREIGN KEY ("CONDR_IDSEQ")
	  REFERENCES "SBREXT"."CON_DERIVATION_RULES_EXT" ("CONDR_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."OBJECT_CLASSES_EXT" ADD CONSTRAINT "OCT_COT_FK" FOREIGN KEY ("CONTE_IDSEQ")
	  REFERENCES "SBR"."CONTEXTS" ("CONTE_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBJECT_CLASSES_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."OBJECT_CLASSES_STAGING" ADD CONSTRAINT "OCS_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OC_RECS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_AC_CSI_FK" FOREIGN KEY ("T_AC_CSI_IDSEQ")
	  REFERENCES "SBR"."AC_CSI" ("AC_CSI_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_AC_CSI_FK2" FOREIGN KEY ("S_AC_CSI_IDSEQ")
	  REFERENCES "SBR"."AC_CSI" ("AC_CSI_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_ASL_FK" FOREIGN KEY ("ASL_NAME")
	  REFERENCES "SBR"."AC_STATUS_LOV" ("ASL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_CONDR_FK" FOREIGN KEY ("S_CONDR_IDSEQ")
	  REFERENCES "SBREXT"."CON_DERIVATION_RULES_EXT" ("CONDR_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_CONDR_FK1" FOREIGN KEY ("CONDR_IDSEQ")
	  REFERENCES "SBREXT"."CON_DERIVATION_RULES_EXT" ("CONDR_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_CONDR_FK2" FOREIGN KEY ("T_CONDR_IDSEQ")
	  REFERENCES "SBREXT"."CON_DERIVATION_RULES_EXT" ("CONDR_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_CONTE_FK" FOREIGN KEY ("CONTE_IDSEQ")
	  REFERENCES "SBR"."CONTEXTS" ("CONTE_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_OCT_FK" FOREIGN KEY ("T_OC_IDSEQ")
	  REFERENCES "SBREXT"."OBJECT_CLASSES_EXT" ("OC_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_OCT_FK2" FOREIGN KEY ("S_OC_IDSEQ")
	  REFERENCES "SBREXT"."OBJECT_CLASSES_EXT" ("OC_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."OC_RECS_EXT" ADD CONSTRAINT "ORT_RL_FK" FOREIGN KEY ("RL_NAME")
	  REFERENCES "SBR"."RELATIONSHIPS_LOV" ("RL_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROPERTIES_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."PROPERTIES_EXT" ADD CONSTRAINT "PROP_ASV_FK" FOREIGN KEY ("ASL_NAME")
	  REFERENCES "SBR"."AC_STATUS_LOV" ("ASL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."PROPERTIES_EXT" ADD CONSTRAINT "PROP_CONDR_FK" FOREIGN KEY ("CONDR_IDSEQ")
	  REFERENCES "SBREXT"."CON_DERIVATION_RULES_EXT" ("CONDR_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."PROPERTIES_EXT" ADD CONSTRAINT "PROP_COT_FK" FOREIGN KEY ("CONTE_IDSEQ")
	  REFERENCES "SBR"."CONTEXTS" ("CONTE_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROPERTIES_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."PROPERTIES_STAGING" ADD CONSTRAINT "PT_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROTOCOLS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."PROTOCOLS_EXT" ADD CONSTRAINT "PROTO_ASV_FK" FOREIGN KEY ("ASL_NAME")
	  REFERENCES "SBR"."AC_STATUS_LOV" ("ASL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."PROTOCOLS_EXT" ADD CONSTRAINT "PROTO_COT_FK" FOREIGN KEY ("CONTE_IDSEQ")
	  REFERENCES "SBR"."CONTEXTS" ("CONTE_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROTOCOL_QC_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."PROTOCOL_QC_EXT" ADD CONSTRAINT "PQ_PROTO_FK" FOREIGN KEY ("PROTO_IDSEQ")
	  REFERENCES "SBREXT"."PROTOCOLS_EXT" ("PROTO_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."PROTOCOL_QC_EXT" ADD CONSTRAINT "PQ_QC_FK" FOREIGN KEY ("QC_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_CONTENTS_EXT" ("QC_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QC_RECS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."QC_RECS_EXT" ADD CONSTRAINT "QRS_RLV_FK" FOREIGN KEY ("RL_NAME")
	  REFERENCES "SBR"."RELATIONSHIPS_LOV" ("RL_NAME") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALIFIER_LOV_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."QUALIFIER_LOV_EXT" ADD CONSTRAINT "QLV_CONDR_FK" FOREIGN KEY ("CON_IDSEQ")
	  REFERENCES "SBREXT"."CONCEPTS_EXT" ("CON_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUEST_ATTRIBUTES_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."QUEST_ATTRIBUTES_EXT" ADD CONSTRAINT "QAT_QCON_FK" FOREIGN KEY ("QCON_IDSEQ")
	  REFERENCES "SBREXT"."QUESTION_CONDITIONS_EXT" ("QCON_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."QUEST_ATTRIBUTES_EXT" ADD CONSTRAINT "QAT_QC_FK" FOREIGN KEY ("QC_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_CONTENTS_EXT" ("QC_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."QUEST_ATTRIBUTES_EXT" ADD CONSTRAINT "QAT_QC_FK2" FOREIGN KEY ("VV_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_CONTENTS_EXT" ("QC_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUEST_CONTENTS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."QUEST_CONTENTS_EXT" ADD CONSTRAINT "QC_ASV_FK" FOREIGN KEY ("ASL_NAME")
	  REFERENCES "SBR"."AC_STATUS_LOV" ("ASL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."QUEST_CONTENTS_EXT" ADD CONSTRAINT "QC_COT_FK" FOREIGN KEY ("CONTE_IDSEQ")
	  REFERENCES "SBR"."CONTEXTS" ("CONTE_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."QUEST_CONTENTS_EXT" ADD CONSTRAINT "QC_DET_FK" FOREIGN KEY ("DE_IDSEQ")
	  REFERENCES "SBR"."DATA_ELEMENTS" ("DE_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."QUEST_CONTENTS_EXT" ADD CONSTRAINT "QC_VPV_FK" FOREIGN KEY ("VP_IDSEQ")
	  REFERENCES "SBR"."VD_PVS" ("VP_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUEST_VV_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."QUEST_VV_EXT" ADD CONSTRAINT "QVT_QC_FK" FOREIGN KEY ("QUEST_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_CONTENTS_EXT" ("QC_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."QUEST_VV_EXT" ADD CONSTRAINT "QVT_QVT_FK" FOREIGN KEY ("VV_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_CONTENTS_EXT" ("QC_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPRESENTATIONS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."REPRESENTATIONS_EXT" ADD CONSTRAINT "REP_ASV_FK" FOREIGN KEY ("ASL_NAME")
	  REFERENCES "SBR"."AC_STATUS_LOV" ("ASL_NAME") ENABLE;
 
  ALTER TABLE "SBREXT"."REPRESENTATIONS_EXT" ADD CONSTRAINT "REP_CONDR_FK" FOREIGN KEY ("CONDR_IDSEQ")
	  REFERENCES "SBREXT"."CON_DERIVATION_RULES_EXT" ("CONDR_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."REPRESENTATIONS_EXT" ADD CONSTRAINT "REP_COT_FK" FOREIGN KEY ("CONTE_IDSEQ")
	  REFERENCES "SBR"."CONTEXTS" ("CONTE_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPRESENTATIONS_STAGING
--------------------------------------------------------

  ALTER TABLE "SBREXT"."REPRESENTATIONS_STAGING" ADD CONSTRAINT "REPR_SDL_FK" FOREIGN KEY ("SDE_ID")
	  REFERENCES "SBREXT"."SOURCE_DATA_LOADS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RULE_FUNCTIONS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."RULE_FUNCTIONS_EXT" ADD CONSTRAINT "RFT_CONDR_FK" FOREIGN KEY ("CONDR_IDSEQ")
	  REFERENCES "SBREXT"."CON_DERIVATION_RULES_EXT" ("CONDR_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SN_QUERY_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."SN_QUERY_EXT" ADD CONSTRAINT "SQT_SAT_FK" FOREIGN KEY ("AL_IDSEQ")
	  REFERENCES "SBREXT"."SN_ALERT_EXT" ("AL_IDSEQ") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SN_RECIPIENT_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."SN_RECIPIENT_EXT" ADD CONSTRAINT "SPT_CONTE_FK" FOREIGN KEY ("CONTE_IDSEQ")
	  REFERENCES "SBR"."CONTEXTS" ("CONTE_IDSEQ") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "SBREXT"."SN_RECIPIENT_EXT" ADD CONSTRAINT "SPT_SRT_FK" FOREIGN KEY ("REP_IDSEQ")
	  REFERENCES "SBREXT"."SN_REPORT_EXT" ("REP_IDSEQ") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "SBREXT"."SN_RECIPIENT_EXT" ADD CONSTRAINT "SPT_UA_FK" FOREIGN KEY ("UA_NAME")
	  REFERENCES "SBR"."USER_ACCOUNTS" ("UA_NAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SN_REPORT_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."SN_REPORT_EXT" ADD CONSTRAINT "SRT_SAT_FK" FOREIGN KEY ("AL_IDSEQ")
	  REFERENCES "SBREXT"."SN_ALERT_EXT" ("AL_IDSEQ") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SN_REP_CONTENTS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."SN_REP_CONTENTS_EXT" ADD CONSTRAINT "SCT_SRT_FK" FOREIGN KEY ("REP_IDSEQ")
	  REFERENCES "SBREXT"."SN_REPORT_EXT" ("REP_IDSEQ") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TA_PROTO_CSI_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."TA_PROTO_CSI_EXT" ADD CONSTRAINT "TPI_AC_CSI_FK" FOREIGN KEY ("AC_CSI_IDSEQ")
	  REFERENCES "SBR"."AC_CSI" ("AC_CSI_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."TA_PROTO_CSI_EXT" ADD CONSTRAINT "TPI_PROTO_FK" FOREIGN KEY ("PROTO_IDSEQ")
	  REFERENCES "SBREXT"."PROTOCOLS_EXT" ("PROTO_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."TA_PROTO_CSI_EXT" ADD CONSTRAINT "TPI_TAT_FK" FOREIGN KEY ("TA_IDSEQ")
	  REFERENCES "SBREXT"."TRIGGERED_ACTIONS_EXT" ("TA_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOOL_OPTIONS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."TOOL_OPTIONS_EXT" ADD CONSTRAINT "TL_UA_FK" FOREIGN KEY ("UA_NAME")
	  REFERENCES "SBR"."USER_ACCOUNTS" ("UA_NAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRIGGERED_ACTIONS_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."TRIGGERED_ACTIONS_EXT" ADD CONSTRAINT "TAT_DE_FK" FOREIGN KEY ("T_DE_IDSEQ")
	  REFERENCES "SBR"."DATA_ELEMENTS" ("DE_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."TRIGGERED_ACTIONS_EXT" ADD CONSTRAINT "TAT_QCON_FK" FOREIGN KEY ("QCON_IDSEQ")
	  REFERENCES "SBREXT"."QUESTION_CONDITIONS_EXT" ("QCON_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."TRIGGERED_ACTIONS_EXT" ADD CONSTRAINT "TAT_QCON_FK2" FOREIGN KEY ("FORCED_QCON_IDSEQ")
	  REFERENCES "SBREXT"."QUESTION_CONDITIONS_EXT" ("QCON_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."TRIGGERED_ACTIONS_EXT" ADD CONSTRAINT "TAT_QC_FK" FOREIGN KEY ("S_QC_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_CONTENTS_EXT" ("QC_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."TRIGGERED_ACTIONS_EXT" ADD CONSTRAINT "TAT_QC_FK2" FOREIGN KEY ("T_QC_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_CONTENTS_EXT" ("QC_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."TRIGGERED_ACTIONS_EXT" ADD CONSTRAINT "TAT_QVT_FK" FOREIGN KEY ("S_QR_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_VV_EXT" ("QV_IDSEQ") ENABLE;
 
  ALTER TABLE "SBREXT"."TRIGGERED_ACTIONS_EXT" ADD CONSTRAINT "TAT_QVT_FK2" FOREIGN KEY ("T_QR_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_VV_EXT" ("QV_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS_LOCKOUT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."USERS_LOCKOUT" ADD CONSTRAINT "UL_UA_FK" FOREIGN KEY ("UA_NAME")
	  REFERENCES "SBR"."USER_ACCOUNTS" ("UA_NAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VALID_VALUES_ATT_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."VALID_VALUES_ATT_EXT" ADD CONSTRAINT "VVT_QC_FK" FOREIGN KEY ("QC_IDSEQ")
	  REFERENCES "SBREXT"."QUEST_CONTENTS_EXT" ("QC_IDSEQ") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VD_PVS_SOURCES_EXT
--------------------------------------------------------

  ALTER TABLE "SBREXT"."VD_PVS_SOURCES_EXT" ADD CONSTRAINT "VPST_VPV_FK" FOREIGN KEY ("VP_IDSEQ")
	  REFERENCES "SBR"."VD_PVS" ("VP_IDSEQ") ENABLE;
--------------------------------------------------------
--  DDL for Package SBREXT_GET_ROW
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SBREXT"."SBREXT_GET_ROW" IS
/******************************************************************************
   NAME:       SBREXT_GET_ROW
   PURPOSE:    This Package holds all the API's to get a single row of data
               from a table

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        10/18/2001  Prerna Aggarwal      1. Created this package



******************************************************************************/

 PROCEDURE GET_VD(
 P_RETURN_CODE	            OUT VARCHAR2
,P_VD_VD_IDSEQ	            IN OUT VARCHAR2
,P_VD_PREFERRED_NAME	    IN OUT VARCHAR2
,P_VD_CONTE_IDSEQ	        IN OUT VARCHAR2
,P_VD_VERSION	            IN OUT NUMBER
,P_VD_PREFERRED_DEFINITION  OUT VARCHAR2
,P_VD_LONG_NAME	            OUT VARCHAR2
,P_VD_ASL_NAME	            OUT VARCHAR2
,P_VD_CD_IDSEQ	            OUT	VARCHAR2
,P_VD_LATEST_VERSION_IND    OUT	VARCHAR2
,P_VD_TYPE_FLAG	            OUT	VARCHAR
,P_VD_DTL_NAME	            OUT	VARCHAR2
,P_VD_FORML_NAME 	        OUT VARCHAR2
,P_VD_UOML_NAME             OUT	VARCHAR2
,P_VD_LOW_VALUE_NUM	    	OUT	VARCHAR2
,P_VD_HIGH_VALUE_NUM	    OUT	VARCHAR2
,P_VD_MIN_LENGTH_NUM	    OUT	NUMBER
,P_VD_MAX_LENGTH_NUM    	OUT	NUMBER
,P_VD_DECIMAL_PLACE 	    OUT	NUMBER
,P_VD_CHAR_SET_NAME	        OUT	VARCHAR2
,P_VD_BEGIN_DATE	        OUT	VARCHAR2
,P_VD_END_DATE	            OUT	VARCHAR2
,P_VD_CHANGE_NOTE	        OUT	VARCHAR2
,P_VD_CREATED_BY	        OUT	VARCHAR2
,P_VD_DATE_CREATED	        OUT	VARCHAR2
,P_VD_MODIFIED_BY	        OUT	VARCHAR2
,P_VD_DATE_MODIFIED	        OUT	VARCHAR2
,P_VD_DELETED_IND	        OUT	VARCHAR2)	;

PROCEDURE GET_VD(
P_RETURN_CODE	            OUT VARCHAR2
,P_VD_VD_IDSEQ	            IN OUT VARCHAR2
,P_VD_PREFERRED_NAME	    IN OUT VARCHAR2
,P_VD_CONTE_IDSEQ	        IN OUT VARCHAR2
,P_VD_VERSION	            IN OUT NUMBER
,P_VD_PREFERRED_DEFINITION  OUT VARCHAR2
,P_VD_LONG_NAME	            OUT VARCHAR2
,P_VD_ASL_NAME	            OUT VARCHAR2
,P_VD_CD_IDSEQ	            OUT	VARCHAR2
,P_VD_LATEST_VERSION_IND    OUT	VARCHAR2
,P_VD_TYPE_FLAG	            OUT	VARCHAR
,P_VD_DTL_NAME	            OUT	VARCHAR2
,P_VD_FORML_NAME 	        OUT VARCHAR2
,P_VD_UOML_NAME             OUT	VARCHAR2
,P_VD_LOW_VALUE_NUM	    	OUT	VARCHAR2
,P_VD_HIGH_VALUE_NUM	    OUT	VARCHAR2
,P_VD_MIN_LENGTH_NUM	    OUT	NUMBER
,P_VD_MAX_LENGTH_NUM    	OUT	NUMBER
,P_VD_DECIMAL_PLACE 	    OUT	NUMBER
,P_VD_CHAR_SET_NAME	        OUT	VARCHAR2
,P_VD_BEGIN_DATE	        OUT	VARCHAR2
,P_VD_END_DATE	            OUT	VARCHAR2
,P_VD_CHANGE_NOTE	        OUT	VARCHAR2
,P_VD_CREATED_BY	        OUT	VARCHAR2
,P_VD_DATE_CREATED	        OUT	VARCHAR2
,P_VD_MODIFIED_BY	        OUT	VARCHAR2
,P_VD_DATE_MODIFIED	        OUT	VARCHAR2
,P_VD_DELETED_IND	        OUT	VARCHAR2
,P_VD_REP_IDSEQ        OUT	VARCHAR2
,P_VD_QUALIFIER	        OUT	VARCHAR2
,P_VD_ORIGIN	        OUT	VARCHAR2
,P_VD_CONDR_IDSEQ	        OUT	VARCHAR2);

PROCEDURE GET_CONTEXT(
 P_RETURN_CODE	            OUT VARCHAR2
,P_CT_CONTE_IDSEQ 			IN OUT VARCHAR2
,P_CT_NAME					IN OUT VARCHAR2
,P_CT_VERSION				IN OUT NUMBER
,P_CT_LL_NAME				OUT VARCHAR2
,P_CT_PAL_NAME				OUT VARCHAR2
,P_CT_DESCRIPTION			OUT VARCHAR2
,P_CT_LANGUAGE				OUT VARCHAR2
,P_CT_CREATED_BY			OUT VARCHAR2
,P_CT_DATE_CREATED			OUT VARCHAR2
,P_CT_MODIFIED_BY			OUT VARCHAR2
,P_CT_DATE_MODIFIED			OUT VARCHAR2)	;


PROCEDURE GET_CD(
 P_RETURN_CODE	            OUT VARCHAR2
,P_CD_CD_IDSEQ	            IN OUT VARCHAR2
,P_CD_PREFERRED_NAME	    IN OUT VARCHAR2
,P_CD_CT_IDSEQ	       		IN OUT VARCHAR2
,P_CD_VERSION	            IN OUT NUMBER
,P_CD_PREFERRED_DEFINITION  OUT VARCHAR2
,P_CD_LONG_NAME	            OUT VARCHAR2
,P_CD_ASL_NAME	            OUT VARCHAR2
,P_CD_DIMENSIONALITY        OUT	VARCHAR2
,P_CD_LATEST_VERSION_IND    OUT	VARCHAR2
,P_CD_BEGIN_DATE            OUT	VARCHAR2
,P_CD_END_DATE				OUT	VARCHAR2
,P_CD_CHANGE_NOTE	        OUT VARCHAR2
,P_CD_CREATED_BY	        OUT	VARCHAR2
,P_CD_DATE_CREATED	        OUT	VARCHAR2
,P_CD_MODIFIED_BY	        OUT	VARCHAR2
,P_CD_DATE_MODIFIED	        OUT	VARCHAR2
,P_CD_DELETED_IND	        OUT	VARCHAR2)	;


PROCEDURE GET_DEC(
 P_RETURN_CODE	               OUT VARCHAR2
,P_DEC_DEC_IDSEQ	       	   IN OUT VARCHAR2
,P_DEC_PREFERRED_NAME	       IN OUT VARCHAR2
,P_DEC_CONTE_IDSEQ	           IN OUT VARCHAR2
,P_DEC_VERSION	               IN OUT NUMBER
,P_DEC_PREFERRED_DEFINITION    OUT VARCHAR2
,P_DEC_LONG_NAME	           OUT VARCHAR2
,P_DEC_ASL_NAME	               OUT VARCHAR2
,P_DEC_CD_IDSEQ	               OUT	VARCHAR2
,P_DEC_LATEST_VERSION_IND      OUT	VARCHAR2
,P_DEC_PROPL_NAME              OUT	VARCHAR
,P_DEC_OCL_NAME	               OUT	VARCHAR2
,P_DEC_PROPERTY_QUALIFIER  	   OUT  VARCHAR2
,P_DEC_OBJ_CLASS_QUALIFIER 	   OUT	VARCHAR2
,P_DEC_BEGIN_DATE	           OUT	VARCHAR2
,P_DEC_END_DATE	               OUT	VARCHAR2
,P_DEC_CHANGE_NOTE	           OUT	VARCHAR2
,P_DEC_CREATED_BY	           OUT	VARCHAR2
,P_DEC_DATE_CREATED	           OUT	VARCHAR2
,P_DEC_MODIFIED_BY	           OUT	VARCHAR2
,P_DEC_DATE_MODIFIED	        OUT	VARCHAR2
,P_DEC_DELETED_IND	        	OUT	VARCHAR2)	;


PROCEDURE GET_CON(
 P_RETURN_CODE	               OUT VARCHAR2
,P_CON_CON_IDSEQ	       	   IN OUT VARCHAR2
,P_CON_PREFERRED_NAME	       IN OUT VARCHAR2
,P_CON_CONTE_IDSEQ	            OUT VARCHAR2
,P_CON_VERSION	               IN OUT NUMBER
,P_CON_PREFERRED_DEFINITION    OUT VARCHAR2
,P_CON_LONG_NAME	           OUT VARCHAR2
,P_CON_ASL_NAME	               OUT VARCHAR2
,P_CON_DEFINITION_SOURCE	               OUT	VARCHAR2
,P_CON_LATEST_VERSION_IND      OUT	VARCHAR2
,P_CON_EVS_SOURCE              OUT	VARCHAR2
,P_CON_CON_ID  	   OUT  VARCHAR2
,P_CON_ORIGIN 	   OUT	VARCHAR2
,P_CON_BEGIN_DATE	           OUT	VARCHAR2
,P_CON_END_DATE	               OUT	VARCHAR2
,P_CON_CHANGE_NOTE	           OUT	VARCHAR2
,P_CON_CREATED_BY	           OUT	VARCHAR2
,P_CON_DATE_CREATED	           OUT	VARCHAR2
,P_CON_MODIFIED_BY	           OUT	VARCHAR2
,P_CON_DATE_MODIFIED	        OUT	VARCHAR2
,P_CON_DELETED_IND	        	OUT	VARCHAR2)	;

PROCEDURE GET_VM(
P_RETURN_CODE	            OUT VARCHAR2
,P_VM_SHORT_MEANING         IN OUT VARCHAR2
,P_VM_DESCRIPTION			OUT VARCHAR2
,P_VM_COMMENTS   	        OUT	VARCHAR2
,P_VM_BEGIN_DATE	        OUT	VARCHAR2
,P_VM_END_DATE	            OUT	VARCHAR2
,P_VM_CREATED_BY	        OUT	VARCHAR2
,P_VM_DATE_CREATED	        OUT	VARCHAR2
,P_VM_MODIFIED_BY	        OUT	VARCHAR2
,P_VM_DATE_MODIFIED	        OUT	VARCHAR2)	;


PROCEDURE GET_VM(
P_RETURN_CODE	            OUT VARCHAR2
,P_VM_SHORT_MEANING         IN OUT VARCHAR2
,P_VM_DESCRIPTION			OUT VARCHAR2
,P_VM_COMMENTS   	        OUT	VARCHAR2
,P_VM_BEGIN_DATE	        OUT	VARCHAR2
,P_VM_END_DATE	            OUT	VARCHAR2
,P_VM_CREATED_BY	        OUT	VARCHAR2
,P_VM_DATE_CREATED	        OUT	VARCHAR2
,P_VM_MODIFIED_BY	        OUT	VARCHAR2
,P_VM_DATE_MODIFIED	        OUT	VARCHAR2
,P_VM_CONDR_IDSEQ	        OUT	VARCHAR2
,P_VM_VM_IDSEQ              OUT VARCHAR2)	;


-- Added 4/24/2007 (ScenPro)

	PROCEDURE GET_VM(
	 P_RETURN_CODE	            OUT VARCHAR2
	,P_VM_IDSEQ					IN OUT VARCHAR2
	,P_LONG_NAME 				IN OUT VARCHAR2
	,P_VERSION					IN OUT VARCHAR2
	,P_VM_ID					IN OUT VARCHAR2
	,P_PREFERRED_NAME			OUT VARCHAR2
	,P_PREFERRED_DEFINITION		OUT VARCHAR2
	,P_CONTE_IDSEQ				OUT VARCHAR2
	,P_ASL_NAME					OUT VARCHAR2
	,P_LATEST_VERSION_IND	    OUT VARCHAR2
	,P_CONDR_IDSEQ				OUT VARCHAR2
	,P_DEFINITION_SOURCE		OUT VARCHAR2
	,P_ORIGIN					OUT VARCHAR2
	,P_CHANGE_NOTE	        	OUT VARCHAR2
	,P_BEGIN_DATE	        	OUT VARCHAR2
	,P_END_DATE	            	OUT VARCHAR2
	,P_CREATED_BY	        	OUT	VARCHAR2
	,P_DATE_CREATED	        	OUT	VARCHAR2
	,P_MODIFIED_BY	        	OUT	VARCHAR2
	,P_DATE_MODIFIED	        OUT	VARCHAR2
	)	;

	-- from ScenPro 4/24/2007
	PROCEDURE get_vm_condr(
	   p_con_array IN VARCHAR2
      ,p_return_code OUT VARCHAR2
      ,p_long_name IN OUT VARCHAR2
	  ,p_condr_idseq OUT VARCHAR2
	  ,p_preferred_definition OUT VARCHAR2
	  ,p_action OUT VARCHAR2
    ) ;



PROCEDURE GET_VM(
 P_RETURN_CODE	            OUT VARCHAR2
,P_VM_SHORT_MEANING         IN OUT VARCHAR2
,P_VM_DESCRIPTION			OUT VARCHAR2
,P_VM_COMMENTS   	        OUT	VARCHAR2
,P_VM_BEGIN_DATE	        OUT	VARCHAR2
,P_VM_END_DATE	            OUT	VARCHAR2
,P_VM_CREATED_BY	        OUT	VARCHAR2
,P_VM_DATE_CREATED	        OUT	VARCHAR2
,P_VM_MODIFIED_BY	        OUT	VARCHAR2
,P_VM_DATE_MODIFIED	        OUT	VARCHAR2
,P_VM_CONDR_IDSEQ           OUT VARCHAR2)	;

/*PROCEDURE GET_PV(
P_RETURN_CODE	 			OUT VARCHAR2
,P_PV_PV_IDSEQ              IN OUT VARCHAR2
,P_PV_VALUE                 IN OUT VARCHAR2
,P_PV_SHORT_MEANING         IN OUT VARCHAR2
,P_PV_MEANING_DESCRIPTION   OUT VARCHAR2
,P_PV_HIGH_VALUE_NUM        OUT NUMBER
,P_PV_LOW_VALUE_NUM			OUT NUMBER
,P_PV_BEGIN_DATE            OUT VARCHAR2
,P_PV_END_DATE              OUT VARCHAR2
,P_PV_CREATED_BY            OUT VARCHAR2
,P_PV_DATE_CREATED          OUT VARCHAR2
,P_PV_MODIFIED_BY           OUT VARCHAR2
,P_PV_DATE_MODIFIED         OUT VARCHAR2);*/

PROCEDURE GET_VD_PVS(
P_RETURN_CODE 		 		OUT VARCHAR2
,P_VP_VP_IDSEQ       			IN OUT VARCHAR2
,P_VP_VD_IDSEQ       			IN OUT VARCHAR2
,P_VP_PV_IDSEQ       			IN OUT VARCHAR2
,P_VP_CONTE_IDSEQ				OUT VARCHAR2
,P_VP_CREATED_BY     			OUT VARCHAR2
,P_VP_DATE_CREATED   			OUT VARCHAR2
,P_VP_MODIFIED_BY 				OUT VARCHAR2
,P_VP_DATE_MODIFIED				OUT VARCHAR2);


PROCEDURE GET_DE(
P_RETURN_CODE 		 		OUT VARCHAR2
,P_DE_DE_IDSEQ  			IN OUT VARCHAR2
,P_DE_PREFERRED_NAME		IN OUT VARCHAR2
,P_DE_CONTE_IDSEQ           IN OUT VARCHAR2
,P_DE_VERSION    			IN OUT VARCHAR2
,P_DE_PREFERRED_DEFINITION 	OUT VARCHAR2
,P_DE_LONG_NAME  			OUT VARCHAR2
,P_DE_ASL_NAME  			OUT VARCHAR2
,P_DE_DEC_IDSEQ 			OUT VARCHAR2
,P_DE_VD_IDSEQ 				OUT VARCHAR2
,P_DE_LATEST_VERSION_IND  	OUT VARCHAR2
,P_DE_BEGIN_DATE 			OUT VARCHAR2
,P_DE_END_DATE  			OUT VARCHAR2
,P_DE_CHANGE_NOTE 			OUT VARCHAR2
,P_DE_CREATED_BY  			OUT VARCHAR2
,P_DE_DATE_CREATED			OUT VARCHAR2
,P_DE_MODIFIED_BY 			OUT VARCHAR2
,P_DE_DATE_MODIFIED  		OUT VARCHAR2
,P_DE_DELETED_IND			OUT VARCHAR2);


PROCEDURE GET_ASL(
P_RETURN_CODE	            OUT VARCHAR2
,P_ASL_ASL_NAME				IN OUT VARCHAR2
,P_ASL_DESCRIPTION			OUT VARCHAR2
,P_ASL_COMMENTS   	        OUT	VARCHAR2
,P_ASL_CREATED_BY	        OUT	VARCHAR2
,P_ASL_DATE_CREATED	        OUT	VARCHAR2
,P_ASL_MODIFIED_BY	        OUT	VARCHAR2
,P_ASL_DATE_MODIFIED	    OUT	VARCHAR2)	;


PROCEDURE GET_CS(
P_RETURN_CODE	 				OUT VARCHAR2
, P_CS_CS_IDSEQ  				IN OUT VARCHAR2
, P_CS_PREFERRED_NAME 			IN OUT VARCHAR2
, P_CS_CONTE_IDSEQ  			IN OUT VARCHAR2
, P_CS_VERSION					IN OUT NUMBER
, P_CS_PREFERRED_DEFINITION		OUT VARCHAR2
, P_CS_LONG_NAME          		OUT VARCHAR2
, P_CS_ASL_NAME  				OUT VARCHAR2
, P_CS_LATEST_VERSION_IND		OUT VARCHAR2
, P_CS_CSTL_NAME 				OUT VARCHAR2
, P_CS_CMSL_NAME				OUT VARCHAR2
, P_CS_LABEL_TYPE_FLAG			OUT VARCHAR2
, P_CS_BEGIN_DATE				OUT VARCHAR2
, P_CS_END_DATE					OUT VARCHAR2
, P_CS_CHANGE_NOTE				OUT VARCHAR2
, P_CS_CREATED_BY				OUT VARCHAR2
, P_CS_DATE_CREATED				OUT VARCHAR2
, P_CS_MODIFIED_BY				OUT VARCHAR2
, P_CS_DATE_MODIFIED			OUT VARCHAR2
, P_CS_DELETED_IND				OUT VARCHAR2);


PROCEDURE GET_CSI(
P_RETURN_CODE	  				OUT VARCHAR2
,P_CSI_CSI_IDSEQ				IN OUT VARCHAR2
,P_CSI_NAME       				IN OUT VARCHAR2
,P_CSI_CSITL_NAME     			IN OUT VARCHAR2
,P_CSI_DESCRIPTION    			OUT VARCHAR2
,P_CSI_COMMENTS 				OUT VARCHAR2
,P_CSI_CREATED_BY        		OUT VARCHAR2
,P_CSI_DATE_CREATED   			OUT VARCHAR2
,P_CSI_MODIFIED_BY   			OUT VARCHAR2
,P_CSI_DATE_MODIFIED			OUT VARCHAR2);


PROCEDURE GET_CS_CSI(
P_RETURN_CODE		 			OUT VARCHAR2
,P_CSCSI_CS_CSI_IDSEQ			IN OUT VARCHAR2
,P_CSCSI_CS_IDSEQ		  		IN OUT VARCHAR2
,P_CSCSI_CSI_IDSEQ				IN OUT VARCHAR2
,P_CSCSI_P_CS_CSI_IDSEQ			IN OUT VARCHAR2
,P_CSCSI_LINK_CS_CSI_IDSEQ		OUT VARCHAR2
,P_CSCSI_LABEL					OUT VARCHAR2
,P_CSCSI_DISPLAY_ORDER			OUT NUMBER
,P_CSCSI_CREATED_BY				OUT VARCHAR2
,P_CSCSI_DATE_CREATED			OUT VARCHAR2
,P_CSCSI_MODIFIED_BY			OUT VARCHAR2
,P_CSCSI_DATE_MODIFIED			OUT VARCHAR2);


PROCEDURE GET_AC_CSI(
P_RETURN_CODE		 	 OUT VARCHAR2
,P_ACCSI_AC_CSI_IDSEQ 	 IN OUT VARCHAR2
,P_ACCSI_CS_CSI_IDSEQ 	 IN OUT VARCHAR2
,P_ACCSI_AC_IDSEQ	  	 IN OUT VARCHAR2
,P_ACCSI_CREATED_BY   	 OUT VARCHAR2
,P_ACCSI_DATE_CREATED 	 OUT VARCHAR2
,P_ACCSI_MODIFIED_BY  	 OUT VARCHAR2
,P_ACCSI_DATE_MODIFIED	 OUT VARCHAR2);


PROCEDURE GET_FORML(
P_RETURN_CODE	            OUT VARCHAR2
,P_FORML_FORML_NAME			IN OUT VARCHAR2
,P_FORML_DESCRIPTION		OUT VARCHAR2
,P_FORML_COMMENTS   	    OUT	VARCHAR2
,P_FORML_CREATED_BY	        OUT	VARCHAR2
,P_FORML_DATE_CREATED	    OUT	VARCHAR2
,P_FORML_MODIFIED_BY	    OUT	VARCHAR2
,P_FORML_DATE_MODIFIED	    OUT	VARCHAR2)	;

PROCEDURE GET_UOML(
P_RETURN_CODE	            OUT VARCHAR2
,P_UOML_UOML_NAME			IN OUT VARCHAR2
,P_UOML_DESCRIPTION			OUT VARCHAR2
,P_UOML_COMMENTS   	        OUT	VARCHAR2
,P_UOML_CREATED_BY	        OUT	VARCHAR2
,P_UOML_DATE_CREATED	    OUT	VARCHAR2
,P_UOML_MODIFIED_BY	        OUT	VARCHAR2
,P_UOML_DATE_MODIFIED	    OUT	VARCHAR2)	;

PROCEDURE GET_QCDL(
P_RETURN_CODE	        OUT VARCHAR2
,P_QCDL_QCDL_NAME		IN OUT VARCHAR2
,P_QCDL_DESCRIPTION		OUT VARCHAR2
,P_QCDL_COMMENTS   	    OUT	VARCHAR2
,P_QCDL_CREATED_BY	    OUT	VARCHAR2
,P_QCDL_DATE_CREATED	OUT	VARCHAR2
,P_QCDL_MODIFIED_BY	    OUT	VARCHAR2
,P_QCDL_DATE_MODIFIED	OUT	VARCHAR2);

PROCEDURE GET_CHAR_SET(
P_RETURN_CODE	            OUT VARCHAR2
,P_CHAR_SET_CHAR_SET_NAME	IN OUT VARCHAR2
,P_CHAR_SET_DESCRIPTION		OUT VARCHAR2
,P_CHAR_SET_CREATED_BY	    OUT	VARCHAR2
,P_CHAR_SET_DATE_CREATED	OUT	VARCHAR2
,P_CHAR_SET_MODIFIED_BY	    OUT	VARCHAR2
,P_CHAR_SET_DATE_MODIFIED	OUT	VARCHAR2);

PROCEDURE GET_DTL(
P_RETURN_CODE	            OUT VARCHAR2
,P_DTL_DTL_NAME			IN OUT VARCHAR2
,P_DTL_DESCRIPTION			OUT VARCHAR2
,P_DTL_COMMENTS   	        OUT	VARCHAR2);

PROCEDURE GET_DCTL(
P_RETURN_CODE	            OUT VARCHAR2
,P_DCTL_DCTL_NAME		IN OUT VARCHAR2
,P_DCTL_DESCRIPTION			OUT VARCHAR2
,P_DCTL_COMMENTS   	        OUT	VARCHAR2
,P_DCTL_CREATED_BY	        OUT	VARCHAR2
,P_DCTL_DATE_CREATED	    OUT	VARCHAR2
,P_DCTL_MODIFIED_BY	        OUT	VARCHAR2
,P_DCTL_DATE_MODIFIED	    OUT	VARCHAR2);

PROCEDURE GET_DETL(
P_RETURN_CODE	            OUT VARCHAR2
,P_DETL_DETL_NAME			IN OUT VARCHAR2
,P_DETL_DESCRIPTION			OUT VARCHAR2
,P_DETL_COMMENTS   	        OUT	VARCHAR2
,P_DETL_CREATED_BY	        OUT	VARCHAR2
,P_DETL_DATE_CREATED	    OUT	VARCHAR2
,P_DETL_MODIFIED_BY	        OUT	VARCHAR2
,P_DETL_DATE_MODIFIED	    OUT	VARCHAR2);


PROCEDURE GET_RL(
P_RETURN_CODE	        OUT VARCHAR2
,P_RL_RL_NAME				IN OUT VARCHAR2
,P_RL_DESCRIPTION		OUT VARCHAR2
,P_RL_COMMENTS   	    OUT	VARCHAR2
,P_RL_CREATED_BY	    OUT	VARCHAR2
,P_RL_DATE_CREATED	    OUT	VARCHAR2
,P_RL_MODIFIED_BY	    OUT	VARCHAR2
,P_RL_DATE_MODIFIED	OUT	VARCHAR2);

PROCEDURE GET_RD(
P_RETURN_CODE	        OUT VARCHAR2
,P_RD_RD_IDSEQ			IN OUT VARCHAR2
,P_RD_NAME				IN OUT VARCHAR2
,P_RD_DCTL_NAME			OUT VARCHAR2
,P_RD_AC_IDSEQ			OUT VARCHAR2
,P_RD_ACH_IDSEQ			OUT VARCHAR2
,P_RD_AR_IDSEQ			OUT VARCHAR2
,P_RD_ORG_IDSEQ			OUT VARCHAR2
,P_RD_RDTL_NAME			OUT VARCHAR2
,P_RD_DOC_TEXT			OUT VARCHAR2
,P_RD_URL				OUT VARCHAR2
,P_RD_CREATED_BY	    OUT	VARCHAR2
,P_RD_DATE_CREATED	    OUT	VARCHAR2
,P_RD_MODIFIED_BY	    OUT	VARCHAR2
,P_RD_DATE_MODIFIED		OUT	VARCHAR2);


PROCEDURE GET_DES(
P_RETURN_CODE	  	    OUT VARCHAR2
,P_DES_DESIG_IDSEQ			IN OUT VARCHAR2
,P_DES_AC_IDSEQ		   IN OUT VARCHAR2
,P_DES_NAME			   IN OUT VARCHAR2
,P_DES_DETL_NAME	   IN	OUT VARCHAR2
,P_DES_CONTE_IDSEQ	   IN OUT VARCHAR2
,P_DES_LAE_NAME			OUT VARCHAR2
,P_DES_CREATED_BY	    OUT	VARCHAR2
,P_DES_DATE_CREATED		OUT	VARCHAR2
,P_DES_MODIFIED_BY	    OUT	VARCHAR2
,P_DES_DATE_MODIFIED	OUT	VARCHAR2);

PROCEDURE GET_QC(
P_RETURN_CODE	 			OUT VARCHAR2
,P_QC_QC_IDSEQ				IN OUT VARCHAR2
,P_QC_PREFERRED_NAME		IN OUT VARCHAR2
,P_QC_CONTE_IDSEQ			IN OUT VARCHAR2
,P_QC_VERSION				IN OUT NUMBER
,P_QC_PREFERRED_DEFINITION	OUT VARCHAR2
,P_QC_LONG_NAME		 		OUT VARCHAR2
,P_QC_QTL_NAME				OUT VARCHAR2
,P_QC_ASL_NAME				OUT VARCHAR2
,P_QC_PROTO_IDSEQ			OUT VARCHAR2
,P_QC_DE_IDSEQ				OUT VARCHAR2
,P_QC_VP_IDSEQ				OUT VARCHAR2
,P_QC_QC_MATCH_IDSEQ		OUT VARCHAR2
,P_QC_MATCH_IND				OUT VARCHAR2
,P_QC_QC_IDENTIFIER			OUT VARCHAR2
,P_QC_QCDL_NAME             OUT VARCHAR2
,P_QC_LASTEST_VERSION_IND	OUT VARCHAR2
,P_QC_NEW_QC_IND			OUT VARCHAR2
,P_QC_HIGHLIGHT_IND			OUT VARCHAR2
,P_QC_SYSTEM_MSGS			OUT VARCHAR2
,P_QC_REVIEWER_FEEDBACK_EXT	OUT VARCHAR2
,P_QC_REVIEWER_FEEDBACK_ACT OUT VARCHAR2
,P_QC_REVIEWER_FEEDBACK_INT	OUT VARCHAR2
,P_QC_REVIEWED_BY			OUT VARCHAR2
,P_QC_REVIEWED_DATE			OUT VARCHAR2
,P_QC_APPROVED_BY			OUT VARCHAR2
,P_QC_APPROVED_DATE			OUT VARCHAR2
,P_QC_CDE_DICTIONARY_ID		OUT NUMBER
,P_QC_BEGIN_DATE			OUT VARCHAR2
,P_QC_END_DATE				OUT VARCHAR2
,P_QC_CHANGE_NOTE			OUT VARCHAR2
,P_QC_SUB_LONG_NAME			OUT VARCHAR2
,P_QC_GROUP_COMMENTS		OUT VARCHAR2
,P_QC_CREATED_BY			OUT VARCHAR2
,P_QC_DATE_CREATED			OUT VARCHAR2
,P_QC_MODIFIED_BY			OUT VARCHAR2
,P_QC_DATE_MODIFIED			OUT VARCHAR2
,P_QC_DELETED_IND			OUT VARCHAR2);


PROCEDURE GET_SOURCE(
P_RETURN_CODE	            OUT VARCHAR2
,P_SRC_SRC_NAME				IN OUT VARCHAR2
,P_SRC_DESCRIPTION			OUT VARCHAR2
,P_SRC_CREATED_BY	        OUT	VARCHAR2
,P_SRC_DATE_CREATED	    	OUT	VARCHAR2
,P_SRC_MODIFIED_BY	        OUT	VARCHAR2
,P_SRC_DATE_MODIFIED	    OUT	VARCHAR2);

PROCEDURE GET_QTL(
P_RETURN_CODE	            OUT VARCHAR2
,P_QTL_QTL_NAME				IN OUT VARCHAR2
,P_QTL_DESCRIPTION			OUT VARCHAR2
,P_QTL_CREATED_BY	        OUT	VARCHAR2
,P_QTL_DATE_CREATED	    	OUT	VARCHAR2
,P_QTL_MODIFIED_BY	        OUT	VARCHAR2
,P_QTL_DATE_MODIFIED	    OUT	VARCHAR2);


PROCEDURE GET_TSTL(
P_RETURN_CODE	            OUT VARCHAR2
,P_TSTL_TSTL_NAME			IN OUT VARCHAR2
,P_TSTL_DESCRIPTION			OUT VARCHAR2
,P_TSTL_CREATED_BY	        OUT	VARCHAR2
,P_TSTL_DATE_CREATED	    OUT	VARCHAR2
,P_TSTL_MODIFIED_BY	        OUT	VARCHAR2
,P_TSTL_DATE_MODIFIED	    OUT	VARCHAR2);


PROCEDURE GET_TS(
P_RETURN_CODE	            OUT VARCHAR2
,P_TS_TS_IDSEQ				IN OUT VARCHAR2
,P_TS_QC_IDSEQ				OUT VARCHAR2
,P_TS_TSTL_NAME				OUT VARCHAR2
,P_TS_TS_TEXT				OUT VARCHAR2
,P_TS_TS_SEQ				OUT NUMBER
,P_TS_CREATED_BY	        OUT	VARCHAR2
,P_TS_DATE_CREATED	    	OUT	VARCHAR2
,P_TS_MODIFIED_BY	        OUT	VARCHAR2
,P_TS_DATE_MODIFIED	    	OUT	VARCHAR2);

PROCEDURE GET_AC_SRC(
P_RETURN_CODE 		 	OUT VARCHAR2
,P_ACSRC_ACS_IDSEQ	IN OUT VARCHAR2
,P_ACSRC_AC_IDSEQ		IN OUT VARCHAR2
,P_ACSRC_SRC_NAME		IN OUT VARCHAR2
,P_ACSRC_DATE_SUBMITTED	   OUT VARCHAR2
,P_ACSRC_CREATED_BY		   OUT VARCHAR2
,P_ACSRC_DATE_CREATED	   OUT VARCHAR2
,P_ACSRC_MODIFIED_BY	   OUT VARCHAR2
,P_ACSRC_DATE_MODIFIED	   OUT VARCHAR2);

PROCEDURE GET_REL(
P_RETURN_CODE	            OUT VARCHAR2
,P_REL_TABLE	            IN VARCHAR2
,P_REL_REL_IDSEQ	    IN OUT VARCHAR2
,P_REL_P_IDSEQ	            IN OUT VARCHAR2
,P_REL_C_IDSEQ	            IN OUT VARCHAR2
,P_REL_RL_NAME		    IN OUT VARCHAR2
,P_REL_DISPLAY_ORDER	       OUT NUMBER
,P_REL_CREATED_BY	        OUT	VARCHAR2
,P_REL_DATE_CREATED	        OUT	VARCHAR2
,P_REL_MODIFIED_BY	        OUT	VARCHAR2
,P_REL_DATE_MODIFIED	        OUT	VARCHAR2);

PROCEDURE GET_PROTOCOL(
P_RETURN_CODE	 				OUT VARCHAR2
, P_PROTO_PROTO_IDSEQ			IN OUT VARCHAR2
, P_PROTO_PREFERRED_NAME		IN OUT VARCHAR2
, P_PROTO_CONTE_IDSEQ		  	IN OUT VARCHAR2
, P_PROTO_VERSION				IN OUT NUMBER
, P_PROTO_PREFERRED_DEFINITION	OUT VARCHAR2
, P_PROTO_LONG_NAME				OUT VARCHAR2
, P_PROTO_ASL_NAME				OUT VARCHAR2
, P_PROTO_LATEST_VERSION_IND	OUT VARCHAR2
, P_PROTO_PROTOCOL_ID			OUT VARCHAR2
, P_PROTO_TYPE					OUT VARCHAR2
, P_PROTO_PHASE			 		OUT VARCHAR2
, P_PROTO_LEAD_ORG				OUT VARCHAR2
, P_PROTO_CHANGE_TYPE			OUT VARCHAR2
, P_PROTO_CHANGE_NUMBER			OUT NUMBER
, P_PROTO_REVIEWED_BY			OUT VARCHAR2
, P_PROTO_REVIEWED_DATE			OUT VARCHAR2
, P_PROTO_APPROVED_BY			OUT VARCHAR2
, P_PROTO_APPROVED_DATE			OUT VARCHAR2
, P_PROTO_BEGIN_DATE			OUT VARCHAR2
, P_PROTO_END_DATE				OUT VARCHAR2
, P_PROTO_CHANGE_NOTE			OUT VARCHAR2
, P_PROTO_CREATED_BY			OUT VARCHAR2
, P_PROTO_DATE_CREATED			OUT VARCHAR2
, P_PROTO_MODIFIED_BY			OUT VARCHAR2
, P_PROTO_DATE_MODIFIED			OUT VARCHAR2
, P_PROTO_DELETED_IND			OUT VARCHAR2);


PROCEDURE GET_VP_SRC(
P_RETURN_CODE 		 	OUT VARCHAR2
,P_VPSRC_VPS_IDSEQ	IN OUT VARCHAR2
,P_VPSRC_VP_IDSEQ		IN OUT VARCHAR2
,P_VPSRC_SRC_NAME		IN OUT VARCHAR2
,P_VPSRC_DATE_SUBMITTED	   OUT VARCHAR2
,P_VPSRC_CREATED_BY		   OUT VARCHAR2
,P_VPSRC_DATE_CREATED	   OUT VARCHAR2
,P_VPSRC_MODIFIED_BY	   OUT VARCHAR2
,P_VPSRC_DATE_MODIFIED	   OUT VARCHAR2);

PROCEDURE GET_PV(
P_RETURN_CODE	 			OUT VARCHAR2
,P_PV_PV_IDSEQ              IN OUT VARCHAR2
,P_PV_VALUE                 IN OUT VARCHAR2
,P_PV_VM_IDSEQ         IN OUT VARCHAR2
,P_PV_MEANING_DESCRIPTION   OUT VARCHAR2
,P_PV_HIGH_VALUE_NUM        OUT NUMBER
,P_PV_LOW_VALUE_NUM			OUT NUMBER
,P_PV_BEGIN_DATE            OUT VARCHAR2
,P_PV_END_DATE              OUT VARCHAR2
,P_PV_CREATED_BY            OUT VARCHAR2
,P_PV_DATE_CREATED          OUT VARCHAR2
,P_PV_MODIFIED_BY           OUT VARCHAR2
,P_PV_DATE_MODIFIED         OUT VARCHAR2);


END Sbrext_Get_Row;
 
 
/
